<?php

declare(strict_types=1);
require_once "./../vendor/autoload.php";

use Zbkm\Siwe\SiweMessage;
use Zbkm\Siwe\SiweMessageParams;
use Zbkm\Siwe\SiweMessageParamsBuilder;

ini_set('display_errors', 'Off');

session_start();
header("Content-Type: application/json");

switch ($_GET["action"] ?? "") {
    case "get_siwe_message":
        if (!is_string($_POST["address"])) {
            echo json_encode(["status" => "error", "message" => "Address are required"]);
            exit;
        }

        /** @var string $host */
        $host = $_SERVER["HTTP_HOST"] ?? "localhost";
        /** @var string $uri */
        $uri = $_SERVER["REQUEST_URI"] ?? "";

        // create siwe message params
        $params = SiweMessageParamsBuilder::create()
            ->withAddress($_POST["address"]) // user wallet address
            ->withChainId(1) // chain id
            ->withNotBefore((new DateTime())->add(new DateInterval('PT5M')))
            // If nonce is not specified, it will be generated automatically.
            // ->withNonce(NonceManager::generate())
            ->withDomain($host)
            ->withUri("https://$host$uri")
            ->build();

        // we can save params, message or nonce to use later for verification
        $_SESSION["params"] = $params;

        // the message can be generated on the server side and  sent to the client
        $message = SiweMessage::create($params);
        echo json_encode(["status" => "success", "siwe_message" => $message]);
        break;
    case "authorize":
        if (!is_string($_POST["signature"])) {
            echo json_encode(["status" => "error", "message" => "Signature are required"]);
            exit;
        }

        if (!isset($_SESSION["params"])) {
            echo json_encode(["status" => "error", "message" => "SIWE message was not requested"]);
            exit;
        }

        /** @var SiweMessageParams $params */
        $params = $_SESSION["params"];

        // If we sent params or message to the client, then it is sufficient to receive a signature from them
        // and verify it.
        if (SiweMessage::verify($params, $_POST["signature"])) {
            // Authorization success
            echo json_encode(["status" => "success", "message" => "Authorized"]);
        } else {
            // Authorization failed (signature invalid)
            echo json_encode(["status" => "error", "message" => "Invalid signature"]);
        }
        break;
    default:
        echo json_encode(["status" => "error", "message" => "Invalid action"]);
        break;
}

// The above describes an authorization option where the server generates the message itself and sends it to the client.
//
// However, this is not the only option; it is also possible to send only the nonce to the client so that it can
// generate the message itself. This can be done with createSiweMessage in viem.
// If only the nonce was sent to the client, then the client must send back both the message (generated by the client
// based on the nonce) and the signature.
// $params = SiweMessage::parse($_POST["message"]);
// and verify to validate of the data received
// SiweMessage::validate($params, ["nonce" => $_SESSION["nonce"], "site" => $_SERVER["HTTP_HOST"]])
// && SiweMessage::verify($params, $_POST["signature"])
